#!/bin/bash

pieces="ajraaftjabvfafpbajefarcjablrajubafpjanefajmnabpjafebabifafsbaabfruratiouvvsiptuvewstcugwlwouuicwpdlieiidmocipctoelecigoesccgbabcrifaootisddoudmdsggdlddgopddcluplmwlimemicswttpcehutotvhcwetbajvftratuttdchumstcgvvsdwvvdwvwuhewwluhedvlsmsdptemupwtvvdcepemjarprijatdoihltdtmolvwomvcwwvcieesscuhssvtihshltetehwdltdhcdeighrarcjhjaoelhtileoliiosclwcssitpcscptscicilmclshlehhslgvhcwvgppvwrafpjmbalhmmlluhimulcmimsggmpppgpmhpiovmmwpohsewhwqsvwiwvovwvqdofafqbgbamhtguqghucmqitecglstpeclhmsevlompgtlehvgqtohievtvpmedutpfafubhfatplhgiipmqgiemdqsdpmclidsgglodegtohdvohoocsovcucmgoctikgfafiflnalqpliluqghvlddwhpdqdikgdgepkewiehodwhccosugcuuouoegukwlefarwnqnapdhqutkdvkqtwedkqswegpgspuopihpudqchcueqgqkuousqgpmulswprarsncnahqvckwoqqwuwdmewwvdmgttvovmtpkivcslkepkskuupsqgumsgqwsdsrajsnhfavqwhogkqukvgeowkdesothqemklhimwklklmkqtkuikqgsuigtvsdvktjanvfdnawlqdkgqlvlqgwqklsuhqqvqulimvwkpiloektkuokdckuqkdvpuqkompnajongbaqhqgqmkhqkkmkwgkhoqwqviomokvpmkoeqtmumiqcdhmkqedukwqmpkkjajpbraaqnarkjankbajgnabqbaninabkbankjabtnajiranhnarenanwrankrarjaar"
j=0

for (( i=0; i<${#pieces}; i++ )); do
  
  echo -n "${pieces:$i:1}"
  ((j++))
  
  if [ $j -eq 4 ]; then
    echo
    j=0
  fi
done
